spring.application.name=schedulelynx
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/schedulelynx
spring.datasource.username=schedulelynx
spring.datasource.password=schedulelynx

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql
